#############################################################################
# Makefile for building: MyView
# Generated by qmake (2.01a) (Qt 4.7.3) on: Wed Jul 13 20:10:42 2011
# Project:  ../MyView_13_07/MyView.pro
# Template: app
# Command: /home/diogenes/QtSDK/Desktop/Qt/473/gcc/bin/qmake -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ -o Makefile ../MyView_13_07/MyView.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ -I../MyView_13_07 -I../../QtSDK/Desktop/Qt/473/gcc/include/QtCore -I../../QtSDK/Desktop/Qt/473/gcc/include/QtGui -I../../QtSDK/Desktop/Qt/473/gcc/include/QtOpenGL -I../../QtSDK/Desktop/Qt/473/gcc/include -I/usr/X11R6/include -I. -I. -I../MyView_13_07 -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/diogenes/QtSDK/Desktop/Qt/473/gcc/lib
LIBS          = $(SUBLIBS)  -L/home/diogenes/QtSDK/Desktop/Qt/473/gcc/lib -L/usr/X11R6/lib -lQtOpenGL -lQtGui -lQtCore -lGLU -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/diogenes/QtSDK/Desktop/Qt/473/gcc/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../MyView_13_07/main.cpp \
		../MyView_13_07/myview.cpp \
		../MyView_13_07/myitem.cpp moc_myview.cpp \
		moc_myitem.cpp
OBJECTS       = main.o \
		myview.o \
		myitem.o \
		moc_myview.o \
		moc_myitem.o
DIST          = ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf \
		../MyView_13_07/MyView.pro
QMAKE_TARGET  = MyView
DESTDIR       = 
TARGET        = MyView

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_myview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../MyView_13_07/MyView.pro  ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++/qmake.conf ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf \
		../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ -o Makefile ../MyView_13_07/MyView.pro
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/g++.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/unix.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/common/linux.conf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/qconfig.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/modules/qt_webkit_version.pri:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_functions.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt_config.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/exclusive_builds.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_pre.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/release.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/default_post.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/warn_on.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/qt.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/opengl.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/unix/thread.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/moc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/resources.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/uic.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/yacc.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/lex.prf:
../../QtSDK/Desktop/Qt/473/gcc/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -spec ../../QtSDK/Desktop/Qt/473/gcc/mkspecs/linux-g++ -o Makefile ../MyView_13_07/MyView.pro

dist: 
	@$(CHK_DIR_EXISTS) ../MyView_13_07/.tmp/MyView1.0.0 || $(MKDIR) ../MyView_13_07/.tmp/MyView1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) ../MyView_13_07/.tmp/MyView1.0.0/ && $(COPY_FILE) --parents ../MyView_13_07/myview.h ../MyView_13_07/myitem.h ../MyView_13_07/.tmp/MyView1.0.0/ && $(COPY_FILE) --parents ../MyView_13_07/main.cpp ../MyView_13_07/myview.cpp ../MyView_13_07/myitem.cpp ../MyView_13_07/.tmp/MyView1.0.0/ && $(COPY_FILE) --parents ../MyView_13_07/myview.ui ../MyView_13_07/.tmp/MyView1.0.0/ && (cd `dirname ../MyView_13_07/.tmp/MyView1.0.0` && $(TAR) MyView1.0.0.tar MyView1.0.0 && $(COMPRESS) MyView1.0.0.tar) && $(MOVE) `dirname ../MyView_13_07/.tmp/MyView1.0.0`/MyView1.0.0.tar.gz . && $(DEL_FILE) -r ../MyView_13_07/.tmp/MyView1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_myview.cpp moc_myitem.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_myview.cpp moc_myitem.cpp
moc_myview.cpp: ../MyView_13_07/myitem.h \
		../MyView_13_07/myview.h
	/home/diogenes/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) ../MyView_13_07/myview.h -o moc_myview.cpp

moc_myitem.cpp: ../MyView_13_07/myitem.h
	/home/diogenes/QtSDK/Desktop/Qt/473/gcc/bin/moc $(DEFINES) $(INCPATH) ../MyView_13_07/myitem.h -o moc_myitem.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_myview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_myview.h
ui_myview.h: ../MyView_13_07/myview.ui
	/home/diogenes/QtSDK/Desktop/Qt/473/gcc/bin/uic ../MyView_13_07/myview.ui -o ui_myview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: ../MyView_13_07/main.cpp ../MyView_13_07/myview.h \
		../MyView_13_07/myitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../MyView_13_07/main.cpp

myview.o: ../MyView_13_07/myview.cpp ../MyView_13_07/myview.h \
		../MyView_13_07/myitem.h \
		ui_myview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myview.o ../MyView_13_07/myview.cpp

myitem.o: ../MyView_13_07/myitem.cpp ../MyView_13_07/myitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myitem.o ../MyView_13_07/myitem.cpp

moc_myview.o: moc_myview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myview.o moc_myview.cpp

moc_myitem.o: moc_myitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myitem.o moc_myitem.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

